### ISSUE TITLE
Add support for signed settlements / bridging / dispatching

### ISSUE THREAD

**Issue by maht0rz** [proto-kit/framework#142]
**Is your feature request related to a problem? Please describe.**
When running the Protokit sequencer with proofs disabled, the standard settlement contract would not accept the bundle proof (merged blocks into a single proof) due to not being authorized by a real proof. In order to integrate with lightnet or any other live networks, we need signed settlements.

**Describe the solution you'd like**
The permissions on all affected contracts should change to "signature" instead of "proof" for this specific type of operation. This results to being able to deploy the same contract with various permissions depending on the use case (proofs on or off)

**Describe alternatives you've considered**
N/A

**Additional context**
This task is a prerequisite for the lightnet integration into the starter kit.

**Comment by rpanic** [comment]
Todos:

- [ ] Add traceability of sent transactions (mainly return txId and therefore a way to await inclusion)
- [ ] Add monitoring for inclusion / non-inclusion
- [ ] In case of non-inclusion -> retry
- [ ] Set permissions of contracts depending on value of AreProofsEnabled
