### ISSUE TITLE
Improve transaction validation in the mempool

### ISSUE THREAD

**Issue by maht0rz** [proto-kit/framework#163]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

- Verify proofs as argument, throw away the tx any proof doesn't verify
- For non-proven appchain deployments, we still need to compile the requires proof, in case it's not a DynamicProof, to be able to validate proofs-as-arguments against that resulting VK. This means that users will have to still produce the proofs that they send to the runtime, but otherwise every use can send unrestricted public input/outputs to the runtime and potentially break the system

**Comment by rpanic** [comment]
Also, we should sort the returned transactions when returning the from the mempool, so that multiple transactions from the same sender appear in the correct order

**Comment by rpanic** [comment]
We should also add a configurable maximum block size that the mempool respects
