### ISSUE TITLE
Unpublish @proto-kit/stack from npm

### ISSUE THREAD

**Issue by maht0rz** [proto-kit/framework#192]
This package is internal, and was not meant to be published, find a way to unpublish it from NPM.

**Comment by rpanic** [comment]
Also, make that package `private: true`, so that this doesn't happen again in the future

**Comment by ejMina226** [comment]
I think if you do npm unpublish @proto-kit/stack --force then it should work.  I don't have permissions so it won't work if I do it. This command should work if we satisfy the following conditions:
1) no other packages in the npm Public Registry depend on it
2) it had less than 300 downloads over the last week
3) it has a single owner/maintainer

**Comment by rpanic** [comment]
Command worked, package unpublished
